[2025-03-21T18:03:14.164+0500] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-21T18:03:14.173+0500] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_google_maps.fetch_google_maps_data_task manual__2025-03-21T13:03:10.144553+00:00 [queued]>
[2025-03-21T18:03:14.178+0500] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_google_maps.fetch_google_maps_data_task manual__2025-03-21T13:03:10.144553+00:00 [queued]>
[2025-03-21T18:03:14.179+0500] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-21T18:03:14.193+0500] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): fetch_google_maps_data_task> on 2025-03-21 13:03:10.144553+00:00
[2025-03-21T18:03:14.199+0500] {standard_task_runner.py:72} INFO - Started process 49109 to run task
[2025-03-21T18:03:14.202+0500] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'fetch_google_maps', 'fetch_google_maps_data_task', 'manual__2025-03-21T13:03:10.144553+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/fetch_google_maps.py', '--cfg-path', '/tmp/tmplfdurwr6']
[2025-03-21T18:03:14.203+0500] {standard_task_runner.py:105} INFO - Job 20: Subtask fetch_google_maps_data_task
[2025-03-21T18:03:14.243+0500] {task_command.py:467} INFO - Running <TaskInstance: fetch_google_maps.fetch_google_maps_data_task manual__2025-03-21T13:03:10.144553+00:00 [running]> on host ubuntu
[2025-03-21T18:03:14.295+0500] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='fetch_google_maps' AIRFLOW_CTX_TASK_ID='fetch_google_maps_data_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-21T13:03:10.144553+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-21T13:03:10.144553+00:00'
[2025-03-21T18:03:14.296+0500] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-21T18:03:14.297+0500] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-21T18:03:14.297+0500] {logging_mixin.py:190} INFO - Current task name:fetch_google_maps_data_task state:running start_date:2025-03-21 13:03:14.174052+00:00
[2025-03-21T18:03:14.297+0500] {logging_mixin.py:190} INFO - Dag name:fetch_google_maps and current dag run status:running
[2025-03-21T18:03:14.297+0500] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-21T18:03:15.419+0500] {logging_mixin.py:190} INFO - Fetched Data: {'error_message': 'This API key is not authorized to use this service or API.', 'html_attributions': [], 'results': [], 'status': 'REQUEST_DENIED'}
[2025-03-21T18:03:15.419+0500] {python.py:240} INFO - Done. Returned value was: None
[2025-03-21T18:03:15.426+0500] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-21T18:03:15.427+0500] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=fetch_google_maps, task_id=fetch_google_maps_data_task, run_id=manual__2025-03-21T13:03:10.144553+00:00, execution_date=20250321T130310, start_date=20250321T130314, end_date=20250321T130315
[2025-03-21T18:03:15.454+0500] {logging_mixin.py:190} INFO - Task instance in success state
[2025-03-21T18:03:15.454+0500] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-03-21T18:03:15.454+0500] {logging_mixin.py:190} INFO - Dag name:fetch_google_maps queued_at:2025-03-21 13:03:10.156248+00:00
[2025-03-21T18:03:15.455+0500] {logging_mixin.py:190} INFO - Task hostname:ubuntu operator:PythonOperator
[2025-03-21T18:03:15.500+0500] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-21T18:03:15.519+0500] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-21T18:03:15.520+0500] {local_task_job_runner.py:245} INFO - ::endgroup::
