[2025-03-21T21:04:04.735+0500] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-21T21:04:04.749+0500] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: coldpath_ingestion.ingest_cold_twitter_data manual__2025-03-21T16:03:10.154733+00:00 [queued]>
[2025-03-21T21:04:04.756+0500] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: coldpath_ingestion.ingest_cold_twitter_data manual__2025-03-21T16:03:10.154733+00:00 [queued]>
[2025-03-21T21:04:04.756+0500] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-21T21:04:04.771+0500] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): ingest_cold_twitter_data> on 2025-03-21 16:03:10.154733+00:00
[2025-03-21T21:04:04.777+0500] {standard_task_runner.py:72} INFO - Started process 105941 to run task
[2025-03-21T21:04:04.782+0500] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'coldpath_ingestion', 'ingest_cold_twitter_data', 'manual__2025-03-21T16:03:10.154733+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/coldpath.py', '--cfg-path', '/tmp/tmpy_rtr7pm']
[2025-03-21T21:04:04.783+0500] {standard_task_runner.py:105} INFO - Job 34: Subtask ingest_cold_twitter_data
[2025-03-21T21:04:04.822+0500] {task_command.py:467} INFO - Running <TaskInstance: coldpath_ingestion.ingest_cold_twitter_data manual__2025-03-21T16:03:10.154733+00:00 [running]> on host ubuntu
[2025-03-21T21:04:04.887+0500] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='coldpath_ingestion' AIRFLOW_CTX_TASK_ID='ingest_cold_twitter_data' AIRFLOW_CTX_EXECUTION_DATE='2025-03-21T16:03:10.154733+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-21T16:03:10.154733+00:00'
[2025-03-21T21:04:04.888+0500] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-21T21:04:04.888+0500] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-21T21:04:04.888+0500] {logging_mixin.py:190} INFO - Current task name:ingest_cold_twitter_data state:running start_date:2025-03-21 16:04:04.749757+00:00
[2025-03-21T21:04:04.889+0500] {logging_mixin.py:190} INFO - Dag name:coldpath_ingestion and current dag run status:running
[2025-03-21T21:04:04.889+0500] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-21T21:04:46.741+0500] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/tashi/airflow/dags/coldpath.py", line 15, in run_coldpath_script
    subprocess.run(["python3", script_name], check=True)
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['python3', '/home/tashi/BDM_Project/data_ingestion/cold_paths/ingest_cold_twitter_data.py']' returned non-zero exit status 1.
[2025-03-21T21:04:46.747+0500] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-21T21:04:46.747+0500] {logging_mixin.py:190} INFO - Task start:2025-03-21 16:04:04.749757+00:00 end:2025-03-21 16:04:46.746536+00:00 duration:41.996779
[2025-03-21T21:04:46.747+0500] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): ingest_cold_twitter_data> dag:<DAG: coldpath_ingestion> dagrun:<DagRun coldpath_ingestion @ 2025-03-21 16:03:10.154733+00:00: manual__2025-03-21T16:03:10.154733+00:00, state:running, queued_at: 2025-03-21 16:03:10.170219+00:00. externally triggered: True>
[2025-03-21T21:04:46.747+0500] {logging_mixin.py:190} INFO - Failure caused by Command '['python3', '/home/tashi/BDM_Project/data_ingestion/cold_paths/ingest_cold_twitter_data.py']' returned non-zero exit status 1.
[2025-03-21T21:04:46.748+0500] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=coldpath_ingestion, task_id=ingest_cold_twitter_data, run_id=manual__2025-03-21T16:03:10.154733+00:00, execution_date=20250321T160310, start_date=20250321T160404, end_date=20250321T160446
[2025-03-21T21:04:46.777+0500] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-21T21:04:46.777+0500] {standard_task_runner.py:124} ERROR - Failed to execute job 34 for task ingest_cold_twitter_data (Command '['python3', '/home/tashi/BDM_Project/data_ingestion/cold_paths/ingest_cold_twitter_data.py']' returned non-zero exit status 1.; 105941)
Traceback (most recent call last):
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/tashi/airflow/dags/coldpath.py", line 15, in run_coldpath_script
    subprocess.run(["python3", script_name], check=True)
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['python3', '/home/tashi/BDM_Project/data_ingestion/cold_paths/ingest_cold_twitter_data.py']' returned non-zero exit status 1.
[2025-03-21T21:04:46.796+0500] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-21T21:04:46.805+0500] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-21T21:04:46.806+0500] {local_task_job_runner.py:245} INFO - ::endgroup::
