[2025-03-21T17:48:29.274+0500] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-21T17:48:29.283+0500] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_bluesky.ingest_bluesky manual__2025-03-21T12:48:25.246062+00:00 [queued]>
[2025-03-21T17:48:29.288+0500] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_bluesky.ingest_bluesky manual__2025-03-21T12:48:25.246062+00:00 [queued]>
[2025-03-21T17:48:29.288+0500] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-21T17:48:29.306+0500] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): ingest_bluesky> on 2025-03-21 12:48:25.246062+00:00
[2025-03-21T17:48:29.313+0500] {standard_task_runner.py:72} INFO - Started process 46674 to run task
[2025-03-21T17:48:29.317+0500] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'fetch_bluesky', 'ingest_bluesky', 'manual__2025-03-21T12:48:25.246062+00:00', '--job-id', '16', '--raw', '--subdir', 'DAGS_FOLDER/fetch_bluesky.py', '--cfg-path', '/tmp/tmpd4r4w551']
[2025-03-21T17:48:29.318+0500] {standard_task_runner.py:105} INFO - Job 16: Subtask ingest_bluesky
[2025-03-21T17:48:29.369+0500] {task_command.py:467} INFO - Running <TaskInstance: fetch_bluesky.ingest_bluesky manual__2025-03-21T12:48:25.246062+00:00 [running]> on host ubuntu
[2025-03-21T17:48:29.422+0500] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='fetch_bluesky' AIRFLOW_CTX_TASK_ID='ingest_bluesky' AIRFLOW_CTX_EXECUTION_DATE='2025-03-21T12:48:25.246062+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-21T12:48:25.246062+00:00'
[2025-03-21T17:48:29.423+0500] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-21T17:48:29.424+0500] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-21T17:48:29.424+0500] {logging_mixin.py:190} INFO - Current task name:ingest_bluesky state:running start_date:2025-03-21 12:48:29.284013+00:00
[2025-03-21T17:48:29.424+0500] {logging_mixin.py:190} INFO - Dag name:fetch_bluesky and current dag run status:running
[2025-03-21T17:48:29.424+0500] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-21T17:48:30.504+0500] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/tashi/.local/lib/python3.10/site-packages/requests/models.py", line 974, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/tashi/airflow/dags/fetch_bluesky.py", line 13, in ingest_bluesky_data
    data = response.json()
  File "/home/tashi/.local/lib/python3.10/site-packages/requests/models.py", line 978, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2025-03-21T17:48:30.510+0500] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-21T17:48:30.511+0500] {logging_mixin.py:190} INFO - Task start:2025-03-21 12:48:29.284013+00:00 end:2025-03-21 12:48:30.510295+00:00 duration:1.226282
[2025-03-21T17:48:30.511+0500] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): ingest_bluesky> dag:<DAG: fetch_bluesky> dagrun:<DagRun fetch_bluesky @ 2025-03-21 12:48:25.246062+00:00: manual__2025-03-21T12:48:25.246062+00:00, state:running, queued_at: 2025-03-21 12:48:25.258758+00:00. externally triggered: True>
[2025-03-21T17:48:30.511+0500] {logging_mixin.py:190} INFO - Failure caused by Expecting value: line 1 column 1 (char 0)
[2025-03-21T17:48:30.512+0500] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=fetch_bluesky, task_id=ingest_bluesky, run_id=manual__2025-03-21T12:48:25.246062+00:00, execution_date=20250321T124825, start_date=20250321T124829, end_date=20250321T124830
[2025-03-21T17:48:30.534+0500] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-21T17:48:30.535+0500] {standard_task_runner.py:124} ERROR - Failed to execute job 16 for task ingest_bluesky (Expecting value: line 1 column 1 (char 0); 46674)
Traceback (most recent call last):
  File "/home/tashi/.local/lib/python3.10/site-packages/requests/models.py", line 974, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/tashi/airflow/dags/fetch_bluesky.py", line 13, in ingest_bluesky_data
    data = response.json()
  File "/home/tashi/.local/lib/python3.10/site-packages/requests/models.py", line 978, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
[2025-03-21T17:48:30.574+0500] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-21T17:48:30.588+0500] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-21T17:48:30.589+0500] {local_task_job_runner.py:245} INFO - ::endgroup::
