[2025-03-21T17:29:37.691+0500] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-21T17:29:37.700+0500] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_twitter.fetch_twitter_data_task scheduled__2025-03-21T11:00:00+00:00 [queued]>
[2025-03-21T17:29:37.706+0500] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_twitter.fetch_twitter_data_task scheduled__2025-03-21T11:00:00+00:00 [queued]>
[2025-03-21T17:29:37.706+0500] {taskinstance.py:2867} INFO - Starting attempt 1 of 1
[2025-03-21T17:29:37.720+0500] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): fetch_twitter_data_task> on 2025-03-21 11:00:00+00:00
[2025-03-21T17:29:37.726+0500] {standard_task_runner.py:72} INFO - Started process 42921 to run task
[2025-03-21T17:29:37.730+0500] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'fetch_twitter', 'fetch_twitter_data_task', 'scheduled__2025-03-21T11:00:00+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/fetch_twitter.py', '--cfg-path', '/tmp/tmptp46uux1']
[2025-03-21T17:29:37.730+0500] {standard_task_runner.py:105} INFO - Job 15: Subtask fetch_twitter_data_task
[2025-03-21T17:29:37.767+0500] {task_command.py:467} INFO - Running <TaskInstance: fetch_twitter.fetch_twitter_data_task scheduled__2025-03-21T11:00:00+00:00 [running]> on host ubuntu
[2025-03-21T17:29:37.836+0500] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='fetch_twitter' AIRFLOW_CTX_TASK_ID='fetch_twitter_data_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-21T11:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-21T11:00:00+00:00'
[2025-03-21T17:29:37.837+0500] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-21T17:29:37.837+0500] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-21T17:29:37.837+0500] {logging_mixin.py:190} INFO - Current task name:fetch_twitter_data_task state:running start_date:2025-03-21 12:29:37.701111+00:00
[2025-03-21T17:29:37.837+0500] {logging_mixin.py:190} INFO - Dag name:fetch_twitter and current dag run status:running
[2025-03-21T17:29:37.838+0500] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-21T17:30:18.484+0500] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/tashi/airflow/dags/fetch_twitter.py", line 32, in fetch_twitter_data
    tweets = api.user_timeline(screen_name="transit", count=10)
  File "/home/tashi/.local/lib/python3.10/site-packages/tweepy/api.py", line 32, in wrapper
    return method(*args, **kwargs)
  File "/home/tashi/.local/lib/python3.10/site-packages/tweepy/api.py", line 45, in wrapper
    return method(*args, **kwargs)
  File "/home/tashi/.local/lib/python3.10/site-packages/tweepy/api.py", line 413, in user_timeline
    return self.request(
  File "/home/tashi/.local/lib/python3.10/site-packages/tweepy/api.py", line 276, in request
    raise TwitterServerError(resp)
tweepy.errors.TwitterServerError: 525 
[2025-03-21T17:30:18.489+0500] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-03-21T17:30:18.489+0500] {logging_mixin.py:190} INFO - Task start:2025-03-21 12:29:37.701111+00:00 end:2025-03-21 12:30:18.489177+00:00 duration:40.788066
[2025-03-21T17:30:18.490+0500] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): fetch_twitter_data_task> dag:<DAG: fetch_twitter> dagrun:<DagRun fetch_twitter @ 2025-03-21 11:00:00+00:00: scheduled__2025-03-21T11:00:00+00:00, state:running, queued_at: 2025-03-21 12:29:35.261067+00:00. externally triggered: False>
[2025-03-21T17:30:18.490+0500] {logging_mixin.py:190} INFO - Failure caused by 525 
[2025-03-21T17:30:18.490+0500] {taskinstance.py:1226} INFO - Marking task as FAILED. dag_id=fetch_twitter, task_id=fetch_twitter_data_task, run_id=scheduled__2025-03-21T11:00:00+00:00, execution_date=20250321T110000, start_date=20250321T122937, end_date=20250321T123018
[2025-03-21T17:30:18.514+0500] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-21T17:30:18.516+0500] {standard_task_runner.py:124} ERROR - Failed to execute job 15 for task fetch_twitter_data_task (525 ; 42921)
Traceback (most recent call last):
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/home/tashi/.local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/home/tashi/airflow/dags/fetch_twitter.py", line 32, in fetch_twitter_data
    tweets = api.user_timeline(screen_name="transit", count=10)
  File "/home/tashi/.local/lib/python3.10/site-packages/tweepy/api.py", line 32, in wrapper
    return method(*args, **kwargs)
  File "/home/tashi/.local/lib/python3.10/site-packages/tweepy/api.py", line 45, in wrapper
    return method(*args, **kwargs)
  File "/home/tashi/.local/lib/python3.10/site-packages/tweepy/api.py", line 413, in user_timeline
    return self.request(
  File "/home/tashi/.local/lib/python3.10/site-packages/tweepy/api.py", line 276, in request
    raise TwitterServerError(resp)
tweepy.errors.TwitterServerError: 525 
[2025-03-21T17:30:18.555+0500] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-21T17:30:18.566+0500] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-21T17:30:18.567+0500] {local_task_job_runner.py:245} INFO - ::endgroup::
[2025-03-21T17:43:40.900+0500] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-21T17:43:40.912+0500] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_twitter.fetch_twitter_data_task scheduled__2025-03-21T11:00:00+00:00 [queued]>
[2025-03-21T17:43:40.919+0500] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_twitter.fetch_twitter_data_task scheduled__2025-03-21T11:00:00+00:00 [queued]>
[2025-03-21T17:43:40.919+0500] {taskinstance.py:2867} INFO - Starting attempt 1 of 4
[2025-03-21T17:43:40.936+0500] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): fetch_twitter_data_task> on 2025-03-21 11:00:00+00:00
[2025-03-21T17:43:40.946+0500] {standard_task_runner.py:72} INFO - Started process 45896 to run task
[2025-03-21T17:43:40.952+0500] {standard_task_runner.py:104} INFO - Running: ['airflow', 'tasks', 'run', 'fetch_twitter', 'fetch_twitter_data_task', 'scheduled__2025-03-21T11:00:00+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/fetch_twitter.py', '--cfg-path', '/tmp/tmpqejy64q8']
[2025-03-21T17:43:40.953+0500] {standard_task_runner.py:105} INFO - Job 14: Subtask fetch_twitter_data_task
[2025-03-21T17:43:40.997+0500] {task_command.py:467} INFO - Running <TaskInstance: fetch_twitter.fetch_twitter_data_task scheduled__2025-03-21T11:00:00+00:00 [running]> on host ubuntu
[2025-03-21T17:43:41.065+0500] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='fetch_twitter' AIRFLOW_CTX_TASK_ID='fetch_twitter_data_task' AIRFLOW_CTX_EXECUTION_DATE='2025-03-21T11:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-21T11:00:00+00:00'
[2025-03-21T17:43:41.067+0500] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-03-21T17:43:41.067+0500] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-03-21T17:43:41.067+0500] {logging_mixin.py:190} INFO - Current task name:fetch_twitter_data_task state:running start_date:2025-03-21 12:43:40.913011+00:00
[2025-03-21T17:43:41.067+0500] {logging_mixin.py:190} INFO - Dag name:fetch_twitter and current dag run status:running
[2025-03-21T17:43:41.068+0500] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-21T17:43:41.622+0500] {logging_mixin.py:190} INFO - Error fetching tweets: 403 Forbidden
453 - You currently have access to a subset of X API V2 endpoints and limited v1.1 endpoints (e.g. media post, oauth) only. If you need access to this endpoint, you may need a different access level. You can learn more here: https://developer.x.com/en/portal/product
[2025-03-21T17:43:41.623+0500] {python.py:240} INFO - Done. Returned value was: None
[2025-03-21T17:43:41.636+0500] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-21T17:43:41.637+0500] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=fetch_twitter, task_id=fetch_twitter_data_task, run_id=scheduled__2025-03-21T11:00:00+00:00, execution_date=20250321T110000, start_date=20250321T124340, end_date=20250321T124341
[2025-03-21T17:43:41.685+0500] {logging_mixin.py:190} INFO - Task instance in success state
[2025-03-21T17:43:41.686+0500] {logging_mixin.py:190} INFO -  Previous state of the Task instance: running
[2025-03-21T17:43:41.686+0500] {logging_mixin.py:190} INFO - Dag name:fetch_twitter queued_at:2025-03-21 12:43:38.610029+00:00
[2025-03-21T17:43:41.686+0500] {logging_mixin.py:190} INFO - Task hostname:ubuntu operator:PythonOperator
[2025-03-21T17:43:41.726+0500] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-21T17:43:41.738+0500] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-21T17:43:41.739+0500] {local_task_job_runner.py:245} INFO - ::endgroup::
